spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          configuration:
            acks: all
            client.id: CoHab-backend
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer

      bindings:
        notification-out-0:
          destination: notification

  threads:
    virtual:
      enabled: true

  application:
    name: CoHab

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${COHAB_DB_CONTAINER_NAME:localhost}:${COHAB_DB_PORT:5432}/${COHAB_DB:cohab}
    username: ${COHAB_DB_USER:magofrays}
    password: ${COHAB_DB_PASSWORD:labubu}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

  data:
    redis:
      timeout: ${REDIS_TIMEOUT:60000}
      port: ${REDIS_PORT:6379}
      host: ${REDIS_CONTAINER_NAME:localhost}

server:
  port: ${COHAB_SERVER_PORT:8080}
  address: 0.0.0.0

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL:INFO}
    by.magofrays: ${LOGGING_LEVEL:INFO}
    org.apache.kafka: ${LOGGING_LEVEL:INFO}

user:
  max-families: 5

family:
  admin-role-name: Админ
  admin-role-value: 100
  user-role-name: Участник
  user-role-value: 10
  max-member-num: 20

kafka:
  topics:
    notification: "notification"

redis:
  cache:
    ttl: ${JWT_EXPIRES_AT:86400}

security:
  jwt:
    public-key: file:src/main/resources/certs/public.pem
    private-key: file:src/main/resources/certs/private.pem
    expires-at: ${JWT_EXPIRES_AT:86400}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
    allowed-methods: ${ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: "cohab-family"
    version: "1.0.0"
    description: "service for family and role management"

